### ISSUE TITLE
[Telegram] TypeError: stopListeningMethod is not a function

### ISSUE THREAD

**Issue by phillipadsmith** [phillipadsmith/Kassy#4]
```
[   5508.65] TypeError: stopListeningMethod is not a function
                 at Object.exports.stop (facebook.js:167:2)
                 at Platform.shutdown (platform.js:186:36)
                 at exports.run (restart.js:8:7)
                 at Platform.messageRxd (platform.js:56:49)
                 at .<anonymous> (telegram.js:35:9)
                 at emitOne (events.js:96:13)
                 at emit (events.js:188:7)
                 at TelegramBot._processUpdate (/home/beautifulrising/BeautifulRisingBot/node_modules/node-telegram-bot-api/src/telegram.js:78:10)
                 at .<anonymous> (/home/beautifulrising/BeautifulRisingBot/node_modules/node-telegram-bot-api/src/telegramPolling.js:36:14)
                 at Array.forEach (native)
                 at .<anonymous> (/home/beautifulrising/BeautifulRisingBot/node_modules/node-telegram-bot-api/src/telegramPolling.js:33:15)
                 at tryCatcher (/home/beautifulrising/BeautifulRisingBot/node_modules/bluebird/js/main/util.js:26:23)
                 at Promise._settlePromiseFromHandler (/home/beautifulrising/BeautifulRisingBot/node_modules/bluebird/js/main/promise.js:507:31)
                 at Promise._settlePromiseAt (/home/beautifulrising/BeautifulRisingBot/node_modules/bluebird/js/main/promise.js:581:18)
                 at Promise._settlePromises (/home/beautifulrising/BeautifulRisingBot/node_modules/bluebird/js/main/promise.js:697:14)
                 at Async._drainQueue (/home/beautifulrising/BeautifulRisingBot/node_modules/bluebird/js/main/async.js:123:16)
                 at Async._drainQueues (/home/beautifulrising/BeautifulRisingBot/node_modules/bluebird/js/main/async.js:133:10)
                 at Immediate.Async.drainQueues [as _onImmediate] (/home/beautifulrising/BeautifulRisingBot/node_modules/bluebird/js/main/async.js:15:14)
```

**Comment by phillipadsmith** [comment]
Fixed by https://github.com/concierge/Kassy/pull/185
